spring.cloud.azure.keyvault.secret.property-source-enabled=true
spring.cloud.azure.keyvault.secret.endpoint=https://student-kv.vault.azure.net/
spring.cloud.azure.credential.managed-identity-enabled=true

spring.data.mongodb.uri=${mongodb-url}

